ipmi:
    fan_modes:
      standard:
        registers:
          - "0x30"
          - "0x45"
          - "0x01"
          - "0x00"
      full:
        registers:
          - "0x30"
          - "0x45"
          - "0x01"
          - "0x01"
      optimal:
        registers:
          - "0x30"
          - "0x45"
          - "0x01"
          - "0x02"
      heavy_io:
        registers:
          - "0x30"
          - "0x45"
          - "0x01"
          - "0x03"

    fan_zones:
      - name: "Zone 0"
        description: "CPU Zone"
        registers:
          - "0x30"
          - "0x70"
          - "0x66"
          - "0x01"
          - "0x00"

      - name: "Zone 1"
        description: "Peripherals Zone"
        registers:
          - "0x30"
          - "0x70"
          - "0x66"
          - "0x01"
          - "0x01"